name: Java CI with Maven

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 2  # Timeout the entire job after 2 minutes

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 21 (for Spring Boot project)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build with Maven to create the JAR file
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml


      # Kill any running process on port 80 (or the port your Spring Boot app uses)
#      - name: Kill process on port 8080
#        run: |
#          # Find and kill the process using port 8080
#          pid=$(sudo lsof -t -i:8081)
#          if [ ! -z "$pid" ]; then
#            echo "Killing process using port 8080 (PID: $pid)"
#            sudo kill -9 $pid
#          else
#            echo "No process found using port 8080"
#          fi

      # Execute the Spring Boot app (JAR file)
      - name: Run the Spring Boot application
        run: |
          echo "Running the Spring Boot application..."
          sudo java -jar /home/ubuntu/actions-runner/_work/Sandbox-BE/Sandbox-BE/target/test_project-0.0.1-SNAPSHOT.jar &


